name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Excellent job! keep up the good work"
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
